### ISSUE TITLE
Feature extraction

### ISSUE THREAD

**Issue by Flaick** [facebookresearch/ProcedureVRL#1]
Hello, thank you for the great work. Thought I have a question. Is it possible for you to share the feature extraction code to make the re-producation easily? Thanks!

**Comment by YiwuZhong** [comment]
Hi @Flaick, thanks for your interest in our work. If you're talking about feature extraction using CLIP, it's straightforward to [use a pre-trained CLIP model to extract a feature vector given a video frame](https://github.com/openai/CLIP#usage). As demonstrated in our paper, we sample 1 frame per second.
