### ISSUE TITLE
How to choose the GPU ID for single node training?

### ISSUE THREAD

**Issue by rezaghoddoosian** [facebookresearch/ProcedureVRL#10]
Im trying to run one a single GPU but change the gpu number for training. I se the following but it does not work. 
Can you guide me how I can specify the gpu ID for my run?
PS: I want to run using a single gpu also.

gpu=1
os.environ["CUDA_VISIBLE_DEVICES"] = "{}".format(gpu)

**Comment by YiwuZhong** [comment]
Thanks for your interest @rezaghoddoosian. Please take a look at [the instructions in README](https://github.com/facebookresearch/ProcedureVRL?tab=readme-ov-file#pretraining). Specifically, you can set the flag `NUM_GPUS` to 1.
