### ISSUE TITLE
Question about extracting text embedding for zero-shot evaluation

### ISSUE THREAD

**Issue by ZijiaLewisLu** [facebookresearch/ProcedureVRL#2]
Hi,

Thanks for releasing the code! Your work is very interesting.

I wanted to test your model on my dataset yet ran into some error.

I was testing zero-shot inference, so I followed tools/emb_extract.py to extract embedding of the class names. However, the code uses ViT-L/14 model, which returns feature of 768 dim while the visual feature from model is 512 dim. 

I also tested running the file as it is. I obtained `data/clip_14_step_emb_ht100m_vbphrase.pt`, where the feature has 768 dim yet the provided feature `data/clip_step_emb_ht100m_vbphrase.pth` has 512 dim. 

How should I obtain the 512-dim feature? Did I miss some step?

Thank.

**Comment by YiwuZhong** [comment]
@ZijiaLewisLu thanks for your interests in our work. As demonstrated in Implementation Details in our paper, we used CLIP of ViT-B/16 which has dimension as 512. So you can simply change the model name in the script to reproduce the embeddings.
