### ISSUE TITLE
coin.py missing in datasets

### ISSUE THREAD

**Issue by ptirupat** [facebookresearch/ProcedureVRL#4]
Hello,

In the __init__.py file under lib/datasets you have these two imports.  

```
from .howto100m import Howto100m
from .coin import Coin
```

The coin.py file is missing in the folder and the dataset class in howto100m.py is declared "Howto100m_develop". 
Can you please check this?

**Comment by YiwuZhong** [comment]
Thanks for your interest. Simply change 'Howto100m' to 'Howto100m_develop' and remove the line for coin should work. Updated it just now.
