### ISSUE TITLE
NoModule named "clip"

### ISSUE THREAD

**Issue by rezaghoddoosian** [facebookresearch/ProcedureVRL#5]
I have 2 questions:
1) When I run the zero-shot inference command line, it seems that there are several packages that haven't been installed. "clip" is one of them. Other missing packages are ipdb, pytorchvideo and etc. Am I missing anything in the installation part of your instructions or we are expected to install such packages in addition to your installation steps?

2) Also, L23 of video_model_builder.py inside the lib.models folder causes an error as it cannot find "vit_base_patch16_224":

*L23 of video_model_builder.py: from lib.models.vit import vit_base_patch16_224

I looked into the vit.py and see a  "vit_base_patch16_224_develope" function instead of "vit_base_patch16_224". Is this a typo or I am missing something?

**Comment by YiwuZhong** [comment]
Hi @rezaghoddoosian, thanks for your correction. Those missing packages are not fatal to this project. You can simply install them on your own. And due to the typo, it should be "vit_base_patch16_224_develop". Will update them shortly in the next version.
