### ISSUE TITLE
The way in which video slices are fed into the diffusion model. Is it each as a separate individual?

### ISSUE THREAD

**Issue by PotatoMine236** [facebookresearch/ProcedureVRL#6]
Hello dear author, I still have some questions after reading your paper. Namely, are the video slices fed into the model as separate individuals?

**Comment by YiwuZhong** [comment]
Hi @PotatoMine236, thanks for your interest. Each video clip (e.g., 8 seconds) is fed into the video encoder individually. Then each clip is encoded into an embedding. Over time, the diffusion module takes multiple video embeddings as inputs (e.g., 8 vectors with each representing a video clip) and tries to reconstruct the masked embedding.
