### ISSUE TITLE
在微调coin测试集上的步骤预测时出现的问题

### ISSUE THREAD

**Issue by PotatoMine236** [facebookresearch/ProcedureVRL#8]
载入提供的模型时，显示param的shape不匹配
RuntimeError: Error(s) in loading state_dict for VisionTransformer:
	size mismatch for order_tfm.pad_embedding.weight: copying a param with shape torch.Size([1, 512]) from checkpoint, the shape in current model is torch.Size([1, 768]).
	size mismatch for order_tfm.type_embedding.weight: copying a param with shape torch.Size([2, 512]) from checkpoint, the shape in current model is torch.Size([2, 768]).
	size mismatch for order_tfm.temporalEmbedding.weight: copying a param with shape torch.Size([9, 512]) from checkpoint, the shape in current model is torch.Size([9, 768]).
	size mismatch for order_tfm.temporalModelling.resblocks.0.attn.in_proj_weight: copying a param with shape torch.Size([1536, 512]) from checkpoint, the shape in current model is torch.Size([2304, 768]).
	size mismatch for order_tfm.temporalModelling.resblocks.0.attn.in_proj_bias: copying a param with shape torch.Size([1536]) from checkpoint, the shape in current model is torch.Size([2304]).
	size mismatch for order_tfm.temporalModelling.resblocks.0.attn.out_proj.weight: copying a param with shape torch.Size([512, 512]) from checkpoint, the shape in current model is torch.Size([768, 768]).
	size mismatch for order_tfm.temporalModelling.resblocks.0.attn.out_proj.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([768]).
	size mismatch for order_tfm.temporalModelling.resblocks.0.ln_1.weight: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([768]).
	size mismatch for order_tfm.temporalModelling.resblocks.0.ln_1.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([768]).
	size mismatch for order_tfm.temporalModelling.resblocks.0.mlp.c_fc.weight: copying a param with shape torch.Size([2048, 512]) from checkpoint, the shape in current model is torch.Size([3072, 768]).
	size mismatch for order_tfm.temporalModelling.resblocks.0.mlp.c_fc.bias: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([3072]).
	size mismatch for order_tfm.temporalModelling.resblocks.0.mlp.c_proj.weight: copying a param with shape torch.Size([512, 2048]) from checkpoint, the shape in current model is torch.Size([768, 3072]).
	size mismatch for order_tfm.temporalModelling.resblocks.0.mlp.c_proj.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([768]).
	size mismatch for order_tfm.temporalModelling.resblocks.0.ln_2.weight: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([768]).
	size mismatch for order_tfm.temporalModelling.resblocks.0.ln_2.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([768]).
	size mismatch for order_tfm.temporalModelling.resblocks.1.attn.in_proj_weight: copying a param with shape torch.Size([1536, 512]) from checkpoint, the shape in current model is torch.Size([2304, 768]).
	size mismatch for order_tfm.temporalModelling.resblocks.1.attn.in_proj_bias: copying a param with shape torch.Size([1536]) from checkpoint, the shape in current model is torch.Size([2304]).
	size mismatch for order_tfm.temporalModelling.resblocks.1.attn.out_proj.weight: copying a param with shape torch.Size([512, 512]) from checkpoint, the shape in current model is torch.Size([768, 768]).
	size mismatch for order_tfm.temporalModelling.resblocks.1.attn.out_proj.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([768]).
	size mismatch for order_tfm.temporalModelling.resblocks.1.ln_1.weight: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([768]).
	size mismatch for order_tfm.temporalModelling.resblocks.1.ln_1.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([768]).
	size mismatch for order_tfm.temporalModelling.resblocks.1.mlp.c_fc.weight: copying a param with shape torch.Size([2048, 512]) from checkpoint, the shape in current model is torch.Size([3072, 768]).
	size mismatch for order_tfm.temporalModelling.resblocks.1.mlp.c_fc.bias: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([3072]).
	size mismatch for order_tfm.temporalModelling.resblocks.1.mlp.c_proj.weight: copying a param with shape torch.Size([512, 2048]) from checkpoint, the shape in current model is torch.Size([768, 3072]).
	size mismatch for order_tfm.temporalModelling.resblocks.1.mlp.c_proj.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([768]).
	size mismatch for order_tfm.temporalModelling.resblocks.1.ln_2.weight: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([768]).
	size mismatch for order_tfm.temporalModelling.resblocks.1.ln_2.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([768]).
	size mismatch for order_tfm.temporalModelling.resblocks.2.attn.in_proj_weight: copying a param with shape torch.Size([1536, 512]) from checkpoint, the shape in current model is torch.Size([2304, 768]).
	size mismatch for order_tfm.temporalModelling.resblocks.2.attn.in_proj_bias: copying a param with shape torch.Size([1536]) from checkpoint, the shape in current model is torch.Size([2304]).
	size mismatch for order_tfm.temporalModelling.resblocks.2.attn.out_proj.weight: copying a param with shape torch.Size([512, 512]) from checkpoint, the shape in current model is torch.Size([768, 768]).
	size mismatch for order_tfm.temporalModelling.resblocks.2.attn.out_proj.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([768]).
	size mismatch for order_tfm.temporalModelling.resblocks.2.ln_1.weight: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([768]).
	size mismatch for order_tfm.temporalModelling.resblocks.2.ln_1.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([768]).
	size mismatch for order_tfm.temporalModelling.resblocks.2.mlp.c_fc.weight: copying a param with shape torch.Size([2048, 512]) from checkpoint, the shape in current model is torch.Size([3072, 768]).
	size mismatch for order_tfm.temporalModelling.resblocks.2.mlp.c_fc.bias: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([3072]).
	size mismatch for order_tfm.temporalModelling.resblocks.2.mlp.c_proj.weight: copying a param with shape torch.Size([512, 2048]) from checkpoint, the shape in current model is torch.Size([768, 3072]).
	size mismatch for order_tfm.temporalModelling.resblocks.2.mlp.c_proj.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([768]).
	size mismatch for order_tfm.temporalModelling.resblocks.2.ln_2.weight: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([768]).
	size mismatch for order_tfm.temporalModelling.resblocks.2.ln_2.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([768]).
	size mismatch for order_tfm.temporalModelling.resblocks.3.attn.in_proj_weight: copying a param with shape torch.Size([1536, 512]) from checkpoint, the shape in current model is torch.Size([2304, 768]).
	size mismatch for order_tfm.temporalModelling.resblocks.3.attn.in_proj_bias: copying a param with shape torch.Size([1536]) from checkpoint, the shape in current model is torch.Size([2304]).
	size mismatch for order_tfm.temporalModelling.resblocks.3.attn.out_proj.weight: copying a param with shape torch.Size([512, 512]) from checkpoint, the shape in current model is torch.Size([768, 768]).
	size mismatch for order_tfm.temporalModelling.resblocks.3.attn.out_proj.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([768]).
	size mismatch for order_tfm.temporalModelling.resblocks.3.ln_1.weight: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([768]).
	size mismatch for order_tfm.temporalModelling.resblocks.3.ln_1.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([768]).
	size mismatch for order_tfm.temporalModelling.resblocks.3.mlp.c_fc.weight: copying a param with shape torch.Size([2048, 512]) from checkpoint, the shape in current model is torch.Size([3072, 768]).
	size mismatch for order_tfm.temporalModelling.resblocks.3.mlp.c_fc.bias: copying a param with shape torch.Size([2048]) from checkpoint, the shape in current model is torch.Size([3072]).
	size mismatch for order_tfm.temporalModelling.resblocks.3.mlp.c_proj.weight: copying a param with shape torch.Size([512, 2048]) from checkpoint, the shape in current model is torch.Size([768, 3072]).
	size mismatch for order_tfm.temporalModelling.resblocks.3.mlp.c_proj.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([768]).
	size mismatch for order_tfm.temporalModelling.resblocks.3.ln_2.weight: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([768]).
	size mismatch for order_tfm.temporalModelling.resblocks.3.ln_2.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([768]).
	size mismatch for order_tfm.time_mlp.1.weight: copying a param with shape torch.Size([512, 128]) from checkpoint, the shape in current model is torch.Size([768, 192]).
	size mismatch for order_tfm.time_mlp.1.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([768]).
	size mismatch for order_tfm.time_mlp.3.weight: copying a param with shape torch.Size([512, 512]) from checkpoint, the shape in current model is torch.Size([768, 768]).
	size mismatch for order_tfm.time_mlp.3.bias: copying a param with shape torch.Size([512]) from checkpoint, the shape in current model is torch.Size([768]).

**Comment by PotatoMine236** [comment]
在对coin的step分类任务中没有出现此问题

**Comment by YiwuZhong** [comment]
Hi @PotatoMine236, thanks for your interest in our work. Based on your log, it seems the feature dimension from the video encoder mismatches the dimension of the order transformer. I would suggest looking into the model initialization and check the dimension of `self.head`.
