### ISSUE TITLE
Some problems encountered in fine-tuning

### ISSUE THREAD

**Issue by PotatoMine236** [facebookresearch/ProcedureVRL#9]
Hi author, I see that the file cloned on github gives an emb file clip_step_emb_coin.pth for the coin dataset.
Is this file actually being used? Or was this file ever used to fine-tune the entire network when choosing how to fine-tune the model, and then decided to forget to delete this file by fine-tuning only the head_cls.

**Comment by YiwuZhong** [comment]
Hi @PotatoMine236, this file was used for zero-shot inference on COIN dataset, where the video embeddings were matched to the language embeddings of step candidates.
